### ISSUE TITLE
Null pointer exception when importing xml containing only passing test cases

### ISSUE THREAD

**Issue by maikeffi** [zephyrdeveloper/zfj-jenkins#1]
mporting xUnit XML for a suite of test cases which does not contain a failure results in a Null pointer exception.
Using xml generated from the python unittest framework for a suite with two passing test cases, we encountered a Null pointer exception:
[ZapiTestResultReporter] [INFO] Examining test results...
Build result is SUCCESS
Total Test Cases : 2ERROR: Build step failed with exception
java.lang.NullPointerException
at com.thed.zephyr.jenkins.utils.rest.TestCaseUtil.executeTests(TestCaseUtil.java:331)
at com.thed.zephyr.jenkins.utils.rest.TestCaseUtil.processTestCaseDetails(TestCaseUtil.java:441)
at com.thed.zephyr.jenkins.reporter.ZfjReporter.perform(ZfjReporter.java:98)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
at hudson.model.Build$BuildExecution.post2(Build.java:185)
at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
at hudson.model.Run.execute(Run.java:1766)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:381)
Build step 'Publish test result to Zephyr for JIRA' marked build as failure

**Comment by YongtaoMa** [comment]
The issue can be solved by update the line 332 of the class: com.thed.zephyr.jenkins.utils.rest.TestCaseUtil. The reason is that response will only be initialised if the failList is not empty. So later if the passList is also not empty, the response is to be closed when it will remain null if the failList is empty.

from:
response.close();

to:
if(response!=null){
       response.close();
}

**Comment by maikeffi** [comment]
yup done and dusted !
